# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# C:\Users\dev-admin\aggregate\toolz-feedstock\recipe, last modified Wed Feb 15 03:23:25 2023
# ------------------------------------------------

package:
  name: toolz
  version: 0.12.0
source:
  sha256: 88c570861c440ee3f2f6037c4654613228ff40c93a6c25e0eba70d17282c6194
  url: https://pypi.io/packages/source/t/toolz/toolz-0.12.0.tar.gz
build:
  number: '0'
  script: c:\\ci_311\\toolz_1676431406517\\_h_env\\python.exe -m pip install . -vv
  string: py311haa95532_0
requirements:
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.01.10 haa95532_0
    - certifi 2022.12.7 py311haa95532_0
    - libffi 3.4.2 hd77b12b_6
    - openssl 1.1.1t h2bbff1b_0
    - pip 22.3.1 py311haa95532_0
    - python 3.11.0 h966fe2a_1
    - setuptools 65.5.0 py311haa95532_0
    - sqlite 3.40.1 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2022g h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py311haa95532_0
    - xz 5.2.10 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_0
  run:
    - python >=3.11,<3.12.0a0
test:
  commands:
    - pip check
    - pytest --doctest-modules --pyargs toolz
  imports:
    - tlz
    - toolz
    - toolz.curried
    - toolz.functoolz
    - toolz.sandbox
  requires:
    - pip
    - pytest
about:
  description: 'Toolz provides a set of utility functions for iterators, functions,
    and

    dictionaries. These functions interoperate well and form the building

    blocks of common data analytic operations. They extend the standard

    libraries itertools and functools and borrow heavily from the standard

    libraries of contemporary functional languages.

    '
  dev_url: https://github.com/pytoolz/toolz
  doc_source_url: https://github.com/pytoolz/toolz/blob/master/doc/source/index.rst
  doc_url: https://toolz.readthedocs.io/
  home: https://toolz.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  license_url: https://github.com/pytoolz/toolz/blob/master/LICENSE.txt
  summary: List processing tools and functional utilities
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - eriknw
    - jakirkham
    - jcrist
    - mrocklin
    - ocefpaf
