# This file created by conda-build 3.21.7
# meta.yaml template originally from:
# C:\ci\containers\00002kalde6\tmp\build\80754af9\rsync-recipes\pcre2-10.37-on-winbuilder, last modified Wed Jan  5 11:27:24 2022
# ------------------------------------------------

package:
  name: pcre2
  version: '10.37'
source:
  sha256: 4d95a96e8b80529893b4562be12648d798b957b1ba1aae39606bbc2ab956d270
  url: https://github.com/PhilipHazel/pcre2/releases/download/pcre2-10.37/pcre2-10.37.tar.bz2
build:
  number: '1'
  run_exports:
    - pcre2 >=10.37,<10.38.0a0
  string: h0ff8eda_1
requirements:
  build:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2021.10.26 haa95532_2
    - cmake 3.19.6 h9ad04ae_0
    - libuv 1.40.0 he774522_0
    - lz4-c 1.9.3 h2bbff1b_1
    - m2-base 1.0.0 3
    - m2-bash 4.3.042 5
    - m2-bash-completion 2.3 2
    - m2-catgets 1.1 3
    - m2-coreutils 8.25 102
    - m2-dash 0.5.8 2
    - m2-diffutils 3.3 4
    - m2-file 5.25 2
    - m2-filesystem 2016.04 4
    - m2-findutils 4.6.0 2
    - m2-gawk 4.1.3 2
    - m2-gcc-libs 5.3.0 4
    - m2-gettext 0.19.7 4
    - m2-gmp 6.1.0 3
    - m2-grep 2.22 4
    - m2-gzip 1.7 2
    - m2-inetutils 1.9.2 2
    - m2-info 6.0 2
    - m2-less 481 2
    - m2-libasprintf 0.19.7 4
    - m2-libbz2 1.0.6 3
    - m2-libcatgets 1.1 3
    - m2-libcrypt 1.3 2
    - m2-libgettextpo 0.19.7 4
    - m2-libiconv 1.14 3
    - m2-libintl 0.19.7 4
    - m2-liblzma 5.2.2 2
    - m2-libpcre 8.38 2
    - m2-libreadline 6.3.008 8
    - m2-libutil-linux 2.26.2 2
    - m2-libxml2 2.9.2 3
    - m2-make 4.1 5
    - m2-mintty 1!2.2.3 2
    - m2-mpfr 3.1.4 2
    - m2-msys2-launcher-git 0.3.28.860c495 2
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-ncurses 6.0.20160220 2
    - m2-sed 4.2.2 3
    - m2-tar 1.28 4
    - m2-tftp-hpa 5.2 2
    - m2-time 1.7 2
    - m2-ttyrec 1.0.8 2
    - m2-tzcode 2015.e 2
    - m2-unzip 6.0 3
    - m2-util-linux 2.26.2 2
    - m2-which 2.21 3
    - m2-zip 3.0 2
    - m2-zlib 1.2.8 4
    - msys2-conda-epoch 20160418 1
    - ninja 1.10.2 py39h559b2a2_3
    - openssl 1.1.1l h2bbff1b_0
    - posix 1.0.0 2
    - python 3.9.7 h6244533_1
    - sqlite 3.37.0 h2bbff1b_0
    - tzdata 2021e hda174b7_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
    - xz 5.2.5 h62dcd97_0
    - zlib 1.2.11 h8cc25b3_4
    - zstd 1.4.9 h19a0ad4_0
  host:
    - bzip2 1.0.8 he774522_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - zlib 1.2.11 h8cc25b3_4
  run:
    - bzip2 >=1.0.8,<2.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
    - zlib >=1.2.11,<1.3.0a0
test:
  commands:
    - pcre2test --version
    - pcre2grep --version
    - if not exist %LIBRARY_INC%\\pcre2.h exit 1
    - if not exist %LIBRARY_INC%\\pcre2posix.h exit 1
    - if not exist %LIBRARY_BIN%\\pcre2-8.dll exit 1
    - if not exist %LIBRARY_BIN%\\pcre2-posix.dll exit 1
    - if not exist %LIBRARY_PREFIX%\\lib\\pkgconfig\\libpcre2-posix.pc exit 1
    - if not exist %LIBRARY_PREFIX%\\lib\\pkgconfig\\libpcre2-8.pc exit 1
about:
  description: 'The PCRE library is a set of functions that implement regular expression
    pattern matching

    using the same syntax and semantics as Perl 5. PCRE has its own native API, as
    well as a set of

    wrapper functions that correspond to the POSIX regular expression API. The PCRE
    library is

    free, even for building proprietary software.

    '
  dev_url: https://github.com/PhilipHazel/pcre2
  doc_url: http://www.pcre.org/current/doc/html/
  home: http://www.pcre.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENCE
  summary: Regular expression pattern matching using Perl 5 syntax and semantics.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - dfornika
    - mariusvniekerk
    - xhochy
