#!/bin/sh
_CONDA_ROOT="C:\b\abs_b5q92oum8h\croot\conda_1689272261421\_h_env"
# Copyright (C) 2012 Anaconda, Inc
# SPDX-License-Identifier: BSD-3-Clause
\. "$_CONDA_ROOT/etc/profile.d/conda.sh" || return $?
conda activate "$@"
