# This file created by conda-build 3.21.7
# ------------------------------------------------

package:
  name: yaml-cpp
  version: 0.7.0
source:
  patches:
    - include_yaml-cpp_dll.h.patch
    - include_yaml-cpp_node_detail_node.h.patch
    - yaml-cpp-config.cmake.in.patch
  sha256: 43e6a9fcb146ad871515f0d0873947e5d497a1c9c60c58cb102a97b47208b7c3
  url: https://github.com/jbeder/yaml-cpp/archive/yaml-cpp-0.7.0.tar.gz
build:
  number: 1
  run_exports:
    - yaml-cpp >=0.7.0,<0.8.0a0
  string: hd77b12b_1
requirements:
  build:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2022.2.1 haa95532_0
    - cmake 3.22.1 h9ad04ae_0
    - libffi 3.4.2 h604cdb4_1
    - libuv 1.40.0 he774522_0
    - lz4-c 1.9.3 h2bbff1b_1
    - ninja 1.10.2 py310h6d14046_3
    - openssl 1.1.1m h2bbff1b_0
    - python 3.10.0 h96c0403_3
    - sqlite 3.37.2 h2bbff1b_0
    - tk 8.6.11 h2bbff1b_0
    - tzdata 2021e hda174b7_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
    - xz 5.2.5 h62dcd97_0
    - zlib 1.2.11 h8cc25b3_4
    - zstd 1.5.0 h19a0ad4_1
  host:
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
  run:
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - if not exist %LIBRARY_BIN%\\yaml-cpp.dll exit 1
    - test/test.bat
  files:
    - test
  requires:
    - cmake
    - ninja
    - vs2017_win-64
about:
  dev_url: https://github.com/jbeder/yaml-cpp
  doc_url: https://github.com/jbeder/yaml-cpp.wiki.git
  home: https://github.com/jbeder/yaml-cpp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: yaml-cpp is a YAML parser and emitter in C++ matching the YAML 1.2 spec.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - allanleal
    - marcelotrevisani
    - seanyen
    - tadeu
    - wolfv
