# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# C:\Users\dev-admin\aggregate\conda-content-trust-feedstock\recipe, last modified Wed Feb 15 13:26:25 2023
# ------------------------------------------------

package:
  name: conda-content-trust
  version: 0.1.3
source:
  fn: conda-content-trust-0.1.3.tar.gz
  sha256: 50a2732dcf3612bdff2b36171e3ebc72a74bbc258543a5aa2618218406b30a0d
  url: https://github.com/conda/conda-content-trust/archive/0.1.3.tar.gz
build:
  entry_points:
    - conda-content-trust = conda_content_trust.cli:cli
  number: '0'
  script: c:\\ci_311\\conda-content-trust_1676467587370\\_h_env\\python.exe -m pip
    install --no-deps --ignore-installed -vv .
  string: py311haa95532_0
requirements:
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.01.10 haa95532_0
    - certifi 2022.12.7 py311haa95532_0
    - libffi 3.4.2 hd77b12b_6
    - openssl 1.1.1t h2bbff1b_0
    - pip 22.3.1 py311haa95532_0
    - python 3.11.0 h966fe2a_1
    - setuptools 65.5.0 py311haa95532_0
    - sqlite 3.40.1 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2022g h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py311haa95532_0
    - xz 5.2.10 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_0
  run:
    - cryptography
    - python >=3.11,<3.12.0a0
    - six
test:
  commands:
    - pip check
    - pytest -v tests
    - conda-content-trust --help
  imports:
    - conda_content_trust
  requires:
    - pip
    - pytest
    - pytest-cov
    - ruamel_yaml
  source_files:
    - tests
about:
  dev_url: https://github.com/conda/conda-content-trust
  doc_url: https://github.com/conda/conda-content-trust/blob/main/README.rst
  home: https://github.com/conda/conda-content-trust
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Signing and verification tools for conda
extra:
  copy_test_source_files: true
  final: true
