# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# C:\Users\dev-admin\aggregate\pycosat-feedstock\recipe, last modified Wed Feb 15 05:20:54 2023
# ------------------------------------------------

package:
  name: pycosat
  version: 0.6.4
source:
  sha256: 79ffa99156810e58876dd6374af0b7bff88f9a4580ca8b8468c414c5c2454bb8
  url: https://github.com/conda/pycosat/archive/0.6.4.tar.gz
build:
  number: '0'
  script: c:\\ci_311\\pycosat_1676438455539\\_h_env\\python.exe -m pip install . --no-deps
    -vv
  string: py311h2bbff1b_0
requirements:
  build:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.01.10 haa95532_0
    - certifi 2022.12.7 py311haa95532_0
    - libffi 3.4.2 hd77b12b_6
    - openssl 1.1.1t h2bbff1b_0
    - pip 22.3.1 py311haa95532_0
    - python 3.11.0 h966fe2a_1
    - setuptools 65.5.0 py311haa95532_0
    - sqlite 3.40.1 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2022g h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py311haa95532_0
    - xz 5.2.10 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_0
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.01.10 haa95532_0
    - certifi 2022.12.7 py311haa95532_0
    - libffi 3.4.2 hd77b12b_6
    - openssl 1.1.1t h2bbff1b_0
    - pip 22.3.1 py311haa95532_0
    - python 3.11.0 h966fe2a_1
    - setuptools 65.5.0 py311haa95532_0
    - sqlite 3.40.1 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2022g h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py311haa95532_0
    - xz 5.2.10 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_0
  run:
    - python >=3.11,<3.12.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - pip check
    - python test_package.py "0.6.4"
  files:
    - qg3-08.cnf
    - sudoku.py
    - test_package.py
    - uf20-098.cnf
  imports:
    - pycosat
  requires:
    - pip
about:
  description: 'PicoSAT is a popular SAT solver written by Armin Biere in pure C.
    This

    package provides efficient Python bindings to picosat on the C level, i.e.

    when importing pycosat, the picosat solver becomes part of the Python

    process itself.

    '
  dev_url: https://github.com/conda/pycosat
  doc_source_url: https://github.com/conda/pycosat/blob/master/README.rst
  doc_url: https://pypi.org/project/pycosat/
  home: https://github.com/conda/pycosat
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
  license_url: https://github.com/conda/pycosat/blob/0.6.4/LICENSE
  summary: Bindings to picosat (a SAT solver)
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - kalefranz
    - mcg1969
    - mingwandroid
    - msarahan
    - nehaljwani
    - pelson
