#!/bin/sh
_CONDA_ROOT="E:/BTech/CMRTC/CSE-DS/Academics/Project/Batch04__MajorProject/ADL/_/Program/__0_0_0__/conda/Miniconda"
# Copyright (C) 2012 Anaconda, Inc
# SPDX-License-Identifier: BSD-3-Clause
\echo >&2 "DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'."
\. "$_CONDA_ROOT/etc/profile.d/conda.sh" || return $?
conda deactivate
