# This file created by conda-build 3.22.0
# ------------------------------------------------

package:
  name: libsolv
  version: 0.7.22
source:
  patches:
    - conda_variant_priorization.patch
    - pcre2-compat.patch
    - win_export_and_static_build.patch
  sha256: 968aef452b5493751fa0168cd58745a77c755e202a43fe8d549d791eb16034d5
  url: https://github.com/openSUSE/libsolv/archive/0.7.22.tar.gz
build:
  ignore_run_exports:
    - zlib
  noarch: false
  noarch_python: false
  number: '0'
  script: install_dynamic.bat
  string: h23ce68f_0
requirements:
  build:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2022.07.19 haa95532_0
    - cmake 3.22.1 h9ad04ae_0
    - libffi 3.4.2 hd77b12b_4
    - libuv 1.40.0 he774522_0
    - lz4-c 1.9.3 h2bbff1b_1
    - ninja 1.10.2 haa95532_5
    - ninja-base 1.10.2 h6d14046_5
    - openssl 1.1.1q h2bbff1b_0
    - python 3.10.6 hbb2ffb3_0
    - sqlite 3.39.3 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2022e h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
    - xz 5.2.6 h8cc25b3_0
    - zlib 1.2.12 h8cc25b3_3
    - zstd 1.5.2 h19a0ad4_0
  host:
    - bzip2 1.0.8 he774522_0
    - glib 2.69.1 h5dc1a3c_1
    - libffi 3.4.2 hd77b12b_4
    - libiconv 1.16 h2bbff1b_2
    - pcre 8.45 hd77b12b_0
    - pcre2 10.37 h0ff8eda_1
    - pkg-config 0.29.2 h8cc25b3_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - zlib 1.2.12 h8cc25b3_3
  run:
    - pcre2 >=10.37,<10.38.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - if exist %LIBRARY_INC%\solv\repo.h (exit 0) else (exit 1)
    - if exist %LIBRARY_LIB%\solv.lib (exit 0) else (exit 1)
    - if exist %LIBRARY_LIB%\solvext.lib (exit 0) else (exit 1)
    - if exist %LIBRARY_BIN%\solv.dll (exit 0) else (exit 1)
    - dumpsolv.exe -h
about:
  description: libsolv, a free package dependency solver using a satisfiability algorithm.
  dev_url: https://github.com/openSUSE/libsolv
  doc_src_url: https://github.com/openSUSE/libsolv/tree/master/doc
  doc_url: https://github.com/openSUSE/libsolv/tree/master/doc
  home: https://github.com/openSUSE/libsolv
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.BSD
  summary: Library for solving packages and reading repositories
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 3993f96f-6018-4fe1-8684-66334b146512
  recipe-maintainers:
    - JohanMabille
    - SylvainCorlay
    - adriendelsalle
    - davidbrochart
    - wolfv
  remote_url: git@github.com:AnacondaRecipes/libsolv-feedstock.git
  sha: 0348445259cdf38fc8830e75f23a803cf248f58c
