# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# C:\b\abs_5a9xvt2a3k\clone\recipe, last modified Thu May 25 17:32:21 2023
# ------------------------------------------------

package:
  name: conda-libmamba-solver
  version: 23.5.0
source:
  folder: src/
  sha256: b796a867b4b2d40ab38159681f1db1c287385b85787be5199569d8f08326ca09
  url: https://github.com/conda/conda-libmamba-solver/archive/refs/tags/23.5.0.tar.gz
build:
  number: '0'
  script: C:\\b\\abs_5a9xvt2a3k\\croot\\conda-libmamba-solver_1685032355900\\_h_env\\python.exe
    -m pip install src/ -vv --no-deps --no-build-isolation
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION=23.5.0
  string: py311haa95532_0
requirements:
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.01.10 haa95532_0
    - editables 0.3 py311haa95532_0
    - hatch-vcs 0.2.0 py311haa95532_0
    - hatchling 1.12.2 py311haa95532_0
    - libffi 3.4.4 hd77b12b_0
    - openssl 1.1.1t h2bbff1b_0
    - packaging 23.0 py311haa95532_0
    - pathspec 0.10.3 py311haa95532_0
    - pip 23.0.1 py311haa95532_0
    - pluggy 1.0.0 py311haa95532_1
    - python 3.11.3 h966fe2a_0
    - setuptools 66.0.0 py311haa95532_0
    - setuptools-scm 7.1.0 py311haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - typing-extensions 4.5.0 py311haa95532_0
    - typing_extensions 4.5.0 py311haa95532_0
    - tzdata 2023c h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.38.4 py311haa95532_0
    - xz 5.4.2 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
  run:
    - boltons >=23.0.0
    - conda >=23.5.0
    - libmambapy >=1.4.1
    - python >=3.11,<3.12.0a0
test:
  commands:
    - conda create --solver libmamba -n test --dry-run scipy
  imports:
    - conda_libmamba_solver
about:
  description: 'The conda-libmamba-solver is a new solver for the conda package manager

    which uses the solver from the mamba project behind the scenes,

    while carefully implementing conda''s functionality and expected behaviors on
    top.

    The library used by mamba to do the heavy-lifting is called libsolv.

    '
  dev_url: https://github.com/conda/conda-libmamba-solver
  doc_url: https://conda.github.io/conda-libmamba-solver/
  home: https://github.com/conda/conda-libmamba-solver
  license: BSD-3-Clause
  license_family: BSD
  license_file: src/LICENSE
  summary: The fast mamba solver, now in conda!
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 5adfca4e-36f4-4e28-a8e4-e8f4dc6e6ba8
  recipe-maintainers:
    - jaimergp
    - jezdez
    - wolfv
  remote_url: git@github.com:AnacondaRecipes/conda-libmamba-solver-feedstock.git
  sha: c7d0ef2101c305b2829f1cf25918b938506702ad
  skip-lints:
    - missing_pip_check
