# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# C:\Users\dev-admin\aggregate\brotlipy-feedstock\recipe, last modified Wed Feb 15 01:46:10 2023
# ------------------------------------------------

package:
  name: brotlipy
  version: 0.7.0
source:
  fn: brotlipy-0.7.0.tar.gz
  sha256: 36def0b859beaf21910157b4c33eb3b06d8ce459c942102f16988cca6ea164df
  url: https://pypi.io/packages/source/b/brotlipy/brotlipy-0.7.0.tar.gz
build:
  number: '1002'
  script: python setup.py install --single-version-externally-managed --record=record.txt
  string: py311h2bbff1b_1002
requirements:
  build:
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.01.10 haa95532_0
    - certifi 2022.12.7 py311haa95532_0
    - cffi 1.15.1 py311h2bbff1b_3
    - libffi 3.4.2 hd77b12b_6
    - openssl 1.1.1t h2bbff1b_0
    - pycparser 2.21 pyhd3eb1b0_0
    - python 3.11.0 h966fe2a_1
    - setuptools 65.5.0 py311haa95532_0
    - sqlite 3.40.1 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2022g h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wincertstore 0.2 py311haa95532_0
    - xz 5.2.10 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_0
  run:
    - cffi >=1.0.0
    - python >=3.11,<3.12.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  imports:
    - brotli
about:
  dev_url: https://github.com/python-hyper/brotlipy
  home: https://github.com/python-hyper/brotlipy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python bindings to the Brotli compression library
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - astaric
    - isuruf
    - primozgodec
