# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# C:\b\abs_de215ipd18\clone\recipe, last modified Thu Mar 16 12:15:03 2023
# ------------------------------------------------

package:
  name: pyopenssl
  version: 23.0.0
source:
  sha256: c1cc5f86bcacefc84dada7d31175cae1b1518d5f60d3d0bb595a67822a868a6f
  url: https://pypi.io/packages/source/p/pyopenssl/pyOpenSSL-23.0.0.tar.gz
build:
  number: '0'
  script: C:\\b\\abs_de215ipd18\\croot\\pyopenssl_1678965319166\\_h_env\\python.exe
    -m pip install . -vv --no-deps
  string: py311haa95532_0
requirements:
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.01.10 haa95532_0
    - certifi 2022.12.7 py311haa95532_0
    - libffi 3.4.2 hd77b12b_6
    - openssl 1.1.1t h2bbff1b_0
    - pip 22.3.1 py311haa95532_0
    - python 3.11.0 h966fe2a_3
    - setuptools 65.5.0 py311haa95532_0
    - sqlite 3.41.1 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2022g h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py311haa95532_0
    - xz 5.2.10 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_0
  run:
    - cryptography >=38.0.0,<40
    - python >=3.11,<3.12.0a0
test:
  commands:
    - pip check
    - python -m OpenSSL.debug
  imports:
    - OpenSSL
    - OpenSSL.SSL
    - OpenSSL.crypto
    - OpenSSL.rand
  requires:
    - pip
about:
  description: 'pyOpenSSL is a high-level wrapper around a subset of the OpenSSL library.

    It includes:

    -SSL.Connection objects, wrapping the methods of Python''s portable sockets

    -Callbacks written in Python

    -Extensive error-handling mechanism, mirroring OpenSSL''s error codes

    and much more.

    '
  dev_url: https://github.com/pyca/pyopenssl
  doc_url: https://pyopenssl.readthedocs.org/en/stable/
  home: https://github.com/pyca/pyopenssl
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python wrapper module around the OpenSSL library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: ded7c595-c0cf-470a-8043-12e44bd83fd2
  recipe-maintainers:
    - goanpeca
    - mingwandroid
    - nehaljwani
  remote_url: git@github.com:AnacondaRecipes/pyopenssl-feedstock.git
  sha: eeea5ae1de2e8a67c2bdd06fea99a3dc11c6ed05
