# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# C:\b\abs_a2w_t927qb\clone\recipe, last modified Mon Jun 12 21:11:41 2023
# ------------------------------------------------

package:
  name: pip
  version: 23.1.2
source:
  sha256: 0e7c86f486935893c708287b30bd050a36ac827ec7fe5e43fe7cb198dd835fba
  url: https://pypi.io/packages/source/p/pip/pip-23.1.2.tar.gz
build:
  disable_pip: true
  entry_points:
    - pip = pip._internal.cli.main:main
    - pip3 = pip._internal.cli.main:main
  number: '0'
  string: py311haa95532_0
requirements:
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.05.30 haa95532_0
    - libffi 3.4.4 hd77b12b_0
    - openssl 3.0.8 h2bbff1b_0
    - python 3.11.3 he1021f5_1
    - setuptools 67.8.0 py311haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2023c h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.38.4 py311haa95532_0
    - xz 5.4.2 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
  run:
    - python >=3.11,<3.12.0a0
    - setuptools
    - wheel
test:
  commands:
    - pip -h
    - pip list
  imports:
    - pip
about:
  dev_url: https://github.com/pypa/pip
  doc_url: https://pip.pypa.io/en/stable/
  home: https://pip.pypa.io/en/stable/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: PyPA recommended tool for installing Python packages
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: a2a3221c-c179-447f-bc5e-e11a48d720f8
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
  remote_url: git@github.com:AnacondaRecipes/pip-feedstock.git
  sha: 97984cf8d027ccd2f486b38b3738107c8442af6f
