# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# C:\Users\dev-admin\aggregate\menuinst-feedstock\recipe, last modified Mon Mar 13 17:59:26 2023
# ------------------------------------------------

package:
  name: menuinst
  version: 1.4.19
source:
  fn: menuinst-1.4.19.tar.gz
  sha256: f93ef4bc4e627868b7bba62ef8cb675e84d5bbe69a85a03a7559e1979f3924ec
  url: https://github.com/conda/menuinst/archive/1.4.19.tar.gz
build:
  entry_points:
    - menuinst = menuinst.main:main
  number: '1'
  script:
    - c:\\ci_311\\menuinst_1678730372782\\_h_env\\python.exe -m pip install . -vv
    - copy "%SRC_DIR%\\cwp.py" "%PREFIX%\\"
  skip_compile_pyc:
    - cwp.py
  string: py311h59b6b97_1
requirements:
  build:
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.01.10 haa95532_0
    - certifi 2022.12.7 py311haa95532_0
    - libffi 3.4.2 hd77b12b_6
    - openssl 1.1.1t h2bbff1b_0
    - pip 22.3.1 py311haa95532_0
    - python 3.11.0 h966fe2a_1
    - setuptools 65.5.0 py311haa95532_0
    - sqlite 3.40.1 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2022g h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py311haa95532_0
    - xz 5.2.10 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_0
  run:
    - python >=3.11,<3.12.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - pip check
    - menuinst --help
  imports:
    - menuinst
  requires:
    - pip
about:
  description: 'This application is used by Conda to create shortcuts on a wide variety
    of

    systems.

    '
  dev_url: https://github.com/conda/menuinst
  doc_url: https://github.com/conda/menuinst/wiki
  home: https://github.com/conda/menuinst
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: cross platform install of menu items
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - carlodri
    - goanpeca
    - jakirkham
